parameters:
    newsletter_angular_js:
        assets:
            js:
                moment:
                    - "Resources/public/vendor/moment/min/moment.min.js"
                    - "Resources/public/vendor/moment/locale/fr.js"
                ckeditor:
                    - "Resources/public/vendor/ckeditor/ckeditor.js"
                vendor:
                    - "Resources/public/vendor/jquery/dist/jquery.min.js"
                    - "Resources/public/vendor/jquery-ui/jquery-ui.min.js"
                    - "Resources/public/vendor/angular/angular.min.js"
                    - "Resources/public/vendor/angular-animate/angular-animate.min.js"
                    - "Resources/public/vendor/angular-route/angular-route.min.js"
                    - "Resources/public/vendor/angular-sanitize/angular-sanitize.min.js"
                    - "Resources/public/vendor/angular-toastr/dist/angular-toastr.tpls.min.js"
                    - "Resources/public/vendor/angular-loading-bar/build/loading-bar.min.js"
                    - "Resources/public/vendor/angular-i18n/angular-locale_fr-fr.js"
                    - "Resources/public/vendor/angular-bootstrap/ui-bootstrap-tpls.js"
                    - "Resources/public/vendor/angular-moment/angular-moment.min.js"
                    - "Resources/public/vendor/angular-ckeditor/angular-ckeditor.min.js"
                    - "Resources/public/vendor/ng-idle/angular-idle.min.js"
                    - "Resources/public/vendor/bootstrap/js/dropdown.js"
                    - "Resources/public/vendor/bootstrap/js/alert.js"
                    - "Resources/public/vendor/angular-file-upload/angular-file-upload.min.js"
                app:
                    - "Resources/public/app/app.module.js"
                    - "Resources/public/app/blocks/logger/logger.module.js"
                    - "Resources/public/app/blocks/logger/logger.js"
                    - "Resources/public/app/blocks/router/router.module.js"
                    - "Resources/public/app/blocks/router/routehelper.js"
                    - "Resources/public/app/core/core.module.js"
                    - "Resources/public/app/core/config.js"
                    - "Resources/public/app/core/core.js"
                    - "Resources/public/app/core/model/page.constante.js"
                    - "Resources/public/app/core/model/periodiciteUnite.constante.js"
                    - "Resources/public/app/core/dataservice/destinataire.factory.js"
                    - "Resources/public/app/core/dataservice/listeDiffusion.factory.js"
                    - "Resources/public/app/core/dataservice/campagne.factory.js"
                    - "Resources/public/app/core/dataservice/newsletter.factory.js"
                    #- "Resources/public/app/core/modal/modal.js"
                    - "Resources/public/app/layout/layout.module.js"
                    #- "Resources/public/app/layout/config.route.js"
                    - "Resources/public/app/layout/layout.js"
                    - "Resources/public/app/campit/newsletter/newsletter.module.js"
                    - "Resources/public/app/campit/newsletter/config.route.js"
                    - "Resources/public/app/campit/newsletter/newsletter.js"
                    - "Resources/public/app/campit/newsletter/modal/modalNewsletter.js"
                    - "Resources/public/app/campit/campagne/campagne.module.js"
                    - "Resources/public/app/campit/campagne/config.route.js"
                    - "Resources/public/app/campit/campagne/campagne.js"
                    - "Resources/public/app/campit/destinataire/destinataire.module.js"
                    - "Resources/public/app/campit/destinataire/config.route.js"
                    - "Resources/public/app/campit/destinataire/destinataire.js"
                    - "Resources/public/app/campit/destinataire/modal/modalGestionDestinataire.js"
            css:
                vendor:
                    - "Resources/public/vendor/bootstrap/dist/css/bootstrap.min.css"
                    - "Resources/public/vendor/font-awesome/css/font-awesome.min.css"
                    - "Resources/public/vendor/angular-toastr/dist/angular-toastr.min.css"
                    - "Resources/public/vendor/angular-loading-bar/build/loading-bar.min.css"
                    - "Resources/public/vendor/jquery-ui/themes/base/jquery-ui.min.css"
                app:
                    - "Resources/public/css/style.css"
