test:
    type: rest
    resource: AppBundle\Controller\Rest\TestRestController
    name_prefix:  api_test_
destinataire:
    type: rest
    resource: AppBundle\Controller\Rest\DestinataireRestController
    name_prefix:  api_destinataire_
liste_diffusion:
    type: rest
    resource: AppBundle\Controller\Rest\ListeDiffusionRestController
    name_prefix:  api_liste_diffusion_
newsletter:
    type: rest
    resource: AppBundle\Controller\Rest\NewsletterRestController
    name_prefix:  api_newsletter_
campagne:
    type: rest
    resource: AppBundle\Controller\Rest\CampagneRestController
    name_prefix:  api_campagne_